### PR TITLE
Fix issues with SqlMagic (prettytable) and arrow dependency conflict

### PR DESCRIPTION
**Pull request by ColinMaudry**
Source @allakulov: https://opencontractingint.slack.com/archives/C01H84M900H/p1732121896689579

### CODE REVIEW

**Comment by ColinMaudry** [comment]
I'll fix the linting

**Comment by yolile** [comment]
Thanks, please also remember to clear all outputs https://github.com/open-contracting/notebooks-ocds?tab=readme-ov-file#commit-your-changes

**Comment by ColinMaudry** [comment]
I didn't manage to figure out what is wrong with the CI. `pre-commit` output is all green on my side.

**Comment by ColinMaudry** [comment]
My outputs were clear, I think it's because I was editing locally on VS Code. I'll do a new PR using Colab.

**Pull request closed without merging**
