### PR TITLE
Column renaming

### LINKED ISSUE #25: replace `release_tag` with `tag`
For the release tag section from release_summary, `release_tag` needs to be replaces with `tag`

### PR DESCRIPTION
**Pull request by duncandewhurst**
Closes #25 

I'm updating column names per https://github.com/open-contracting/kingfisher-summarize/pull/196 as I come across them.

### CODE REVIEW

**Comment by jpmckinney** [comment]
FYI, all renames from that PR and subsequent work are in the changelog: https://kingfisher-summarize.readthedocs.io/en/latest/changelog.html

**Comment by duncandewhurst** [comment]
Thanks. I checked all the renames from the changelog and no further changes are required to the notebook.

**Comment by duncandewhurst** [comment]
Only `check_data_quality.ipynb` and `check_scope.ipynb` need reviewing, the other notebooks contain only whitespace changes.

**Comment by duncandewhurst** [comment]
I'm going to merge this PR since the changes are not controversial.

**Pull request merged**
